Added dockerize and deployment stages to pipeline
1058-Sophia-Gavrila-Forge/Forge-Backend pull request #14
Opened 2021-07-21 15:26 UTC by alexanderjervis

added, templated, and parameterized the dockerize and deploy stages in the pipeline. Also moved discord webhook job underneath deployment job so that it is the final job of the pipeline. Docker and AKS are currently using personal resources for testing until we get project resources to replace them.

2021-07-21 17:40 UTC, escalonn commented
@MDarmawan ^ again, avoid commit messages that trigger false github integration behavior

2021-07-21 17:43 UTC, escalonn requested changes

2021-07-21 17:43 UTC, escalonn commented on devops/azure-pipelines/azure-pipelines.yml
> +          serviceConnection: 'Alex-Dev-Cluster'
https://github.com/1058-Sophia-Gavrila-Forge/Portfolio-Frontend/pull/10#discussion_r674195973

2021-07-21 17:43 UTC, escalonn commented on devops/kube/monolith-manifest.yml
> +
random blank lines in this file; i wouldn't reject it over just this, but it does show sloppiness

2021-07-21 22:35 UTC, escalonn approved these changes

2021-07-22 04:06 UTC, MDarmawan approved these changes
Things that could be fixed next iteration: using ACR, maybe using a [deploy job](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs) to support a more advanced deployment strategy (i.e. canary)
Also, since we no longer need the monolith-manifest file, we should delete that...

2021-07-22 04:07 UTC, merged

2021-07-22 15:00 UTC, escalonn commented
> Things that could be fixed next iteration: using ACR, maybe using a [deploy job](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs) to support a more advanced deployment strategy (i.e. canary)
> Also, since we no longer need the monolith-manifest file, we should delete that...

if these things aren't work items, they should be. if you're not 100% that one would be the right choice, then phrase the work item as "evaluate ___"