Add logging to Backend
1058-Sophia-Gavrila-Forge/Forge-Backend pull request #33
Opened 2021-07-31 00:57 UTC by ajang06

Used AOP to:
Log when an exception is thrown in component method
Log when entering and exiting a method using Around Advice

2021-07-31 17:54 UTC, sophiagavrila requested changes
Delete `TestLoggingAspectOld.java` and use `TestLoggingAspect.java` as your full test suite for coverage of LoggingAspect methods.

2021-08-01 14:35 UTC, sophiagavrila requested changes
@ajang06 a few minor smells to resolve before merging:
[Full SonarCloud smell report here](https://sonarcloud.io/project/issues?id=1058-Sophia-Gavrila-Forge_Forge-Backend&pullRequest=33&resolved=false&types=CODE_SMELL)

- [x] remove unused import import `java.util.Arrays;` from `LoggingAspect.java`
- [ ] add some simple logic between lines 85 & 86 in the catch clause (a `log.error(...)` could suffice, or something simple).

2021-08-01 20:25 UTC, FBThornton approved these changes
LGTM!

2021-08-02 13:07 UTC, sophiagavrila approved these changes

2021-08-02 13:08 UTC, merged