Fix user not being ignored in the JSON
1058-Sophia-Gavrila-Forge/Forge-Backend pull request #40
Opened 2021-08-03 20:10 UTC by ddinh

The User object was not being ignored and was included inside the JSON export response. Adding multiple mixins to an ObjectMapper does not work so they were combined into a single JSON ignore mixin.

2021-08-03 20:13 UTC, FBThornton submitted a review, later dismissed

2021-08-04 01:14 UTC, sophiagavrila requested changes
@ddinh  need tests on [these lines of code](https://sonarcloud.io/component_measures?id=1058-Sophia-Gavrila-Forge_Forge-Backend&metric=new_lines_to_cover&pullRequest=40&selected=1058-Sophia-Gavrila-Forge_Forge-Backend%3Asrc%2Fmain%2Fjava%2Fcom%2Fforge%2Frevature%2Fcontrollers%2FPortfolioController.java&view=list)

2021-08-04 01:48 UTC, m-james-butler approved these changes
Looks good now.

2021-08-04 13:53 UTC, sophiagavrila approved these changes

2021-08-04 13:53 UTC, merged